name: Create Release Branch
on:
  schedule:
  # Run every 5 minutes
    - cron: '0/5 0-23 * * *'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create Release Branch
        run: |
          git checkout -b release_$(date +%Y_%m_%d)
          git push origin release_$(date +%Y_%m_%d)


