name: Manually Create Release Branch
on:
  workflow_dispatch
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    env: 
      RELEASE_BRANCH: mobile_release_$(date +%Y_%m_%d)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Check if Release Branch already exists
        id: check-branch
        run: |
          if git ls-remote --heads origin $RELEASE_BRANCH; then
            exit -1
          fi
      - name: Create Release Branch
        run: |
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
      # - name: Send message on Slack
      #   uses: archive/github-actions-slack@v2.0.1
      #   id: notify
      #   with:
      #     slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
      #     slack-channel: C029QPGHSQL
      #     slack-text: Branch `$RELEASE_BRANCH` created for next release.



