name: Manually Create Release Branch
on:
  workflow_dispatch
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    env: 
      RELEASE_BRANCH: mobile_release_$(date +%Y_%m_%d)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Check if release branch exists
        id: check-branch
        run: |
          if git ls-remote --heads origin $RELEASE_BRANCH; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi
      - name: Create release branch
        if: env.branch_exists === 'false'
        run: |
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
          echo "message=Branch $RELEASE_BRANCH created successfully." >> $GITHUB_ENV
      - name: Branch already exists
        if: env.branch_exists === 'true'
        run: echo "message=Branch $RELEASE_BRANCH already exists." >> $GITHUB_ENV
      - name: Send message on Slack
        uses: archive/github-actions-slack@v2.0.1
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C029QPGHSQL
          slack-text: "$message \n Check diff here: https://github.com/fylein/fyle-mobile-app/compare/master...$RELEASE_BRANCH"
